FROM nginx

RUN rm /etc/nginx/conf.d/default.conf

COPY ./default.conf /etc/nginx/conf.d/default.conf

HEALTHCHECK --interval=30s --timeout=30s --start-period=10s --retries=5 CMD curl --fail http://localhost:80 || exit 1
