FROM redis

COPY ./redis-healthcheck /usr/local/bin/redis-healthcheck

RUN chmod +x /usr/local/bin/redis-healthcheck

HEALTHCHECK --interval=30s --timeout=30s --retries=5 --start-period=10s CMD ["redis-healthcheck"]
