#!/bin/bash

source ../../.env

function check_redis_health() {
  set -eo pipefail

  host="$(hostname -i || echo '127.0.0.1')"

  if ping="$(redis-cli -h "$host" ping)" && [ "$ping" = 'PONG' ]; then
	  exit 0
  fi

  exit 1
}

check_redis_health