FROM bash:4.4

COPY healthcheck /usr/local/bin/healthcheck

RUN healthcheck 5 30 server-container
RUN healthcheck 5 30 pg-container
RUN healthcheck 5 30 redis-container
RUN healthcheck 5 30 nginx-container
RUN healthcheck 5 30 amqp-container
