FROM postgres

COPY ./postgres-healthcheck /usr/local/bin/postgres-healthcheck

RUN chmod +x /usr/local/bin/postgres-healthcheck

HEALTHCHECK --interval=30s --timeout=30s --retries=5 --start-period=15s CMD ["postgres-healthcheck"]
