FROM rabbitmq:management-alpine

RUN apk add --no-cache bash

COPY ./amqp-healthcheck /usr/local/bin/amqp-healthcheck

RUN chmod +x /usr/local/bin/amqp-healthcheck

HEALTHCHECK --interval=25s --timeout=30s --start-period=10s --retries=5 CMD ["amqp-healthcheck"]

RUN bash ../script/healthcheck 5 30 rabbitmq-container
